last_update = 1690126858577
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.ply.gg"]
control_address = "control.playit.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "99a4e5462326cd5da3e164615ee5316eb2466f7305987e2505ad5bda025640e7"

[[mappings]]
name = "unnamed"
proto = "both"
tunnel_ip = "147.185.221.16"
tunnel_from_port = 3881
local_port = 5500
